import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "What types of printing services do you offer?",
    answer: "We offer black & white and color printing on various paper types including normal paper, bond paper (80 GSM, 90 GSM, 100 GSM). We specialize in academic document printing with high-quality outputs suitable for thesis, research papers, and projects."
  },
  {
    question: "How long does it take to bind a thesis or dissertation?",
    answer: "Binding time depends on the type of binding and our current queue. Hard binding typically takes 24-48 hours, while soft and spiral binding can usually be completed within a few hours. For urgent requests, we offer express services at an additional charge."
  },
  {
    question: "What is the difference between the types of hard binding?",
    answer: "Normal hard binding uses standard materials suitable for regular use. High-quality binding uses premium materials with better durability. Gloss quality adds a glossy finish to the cover, while emboss quality includes raised text/design on the cover (minimum 4 copies required for emboss binding)."
  },
  {
    question: "How does your plagiarism checking service work?",
    answer: "We use industry-standard tools like Turnitin to check your document against billions of web pages, publications, and student papers. You'll receive a detailed report showing overall similarity percentage and specific matches, allowing you to make necessary changes."
  },
  {
    question: "What is AI plagiarism checking and how is it different?",
    answer: "AI plagiarism checking detects content that may have been generated by AI tools like ChatGPT, which traditional plagiarism checkers might miss. This is increasingly important as many academic institutions are implementing policies against AI-generated content."
  },
  {
    question: "Do you provide academic writing assistance for all subjects?",
    answer: "Yes, we provide academic writing assistance across various disciplines including business, engineering, medicine, humanities, and social sciences. Our team includes subject-matter experts with advanced degrees who can help with thesis writing, research papers, and other academic documents."
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept cash, UPI payments, bank transfers, and major credit/debit cards. For large orders, we may request a partial advance payment."
  },
  {
    question: "Do you offer bulk discounts for printing and binding?",
    answer: "Yes, we offer bulk discounts for orders exceeding specific thresholds. The discount percentage depends on the volume and type of services requested. Please contact us directly for a custom quote for your bulk order."
  },
  {
    question: "Can you deliver printed and bound documents?",
    answer: "For orders above a certain value, we offer delivery services within select areas. Additional delivery charges may apply based on the location. Please inquire about delivery options when placing your order."
  },
  {
    question: "What is your revision policy for plagiarism removal services?",
    answer: "We offer up to two rounds of revisions for our plagiarism removal services at no extra cost if the similarity score remains above the acceptable threshold. Additional revisions may incur extra charges depending on the extent of changes required."
  }
];

const Faq = () => {
  return (
    <section id="faq" className="py-16 bg-white">
      <div className="container px-4 sm:px-6 lg:px-8">
        <div className="text-center max-w-3xl mx-auto mb-12">
          <h2 className="font-serif text-3xl md:text-4xl font-bold text-primary mb-4">Frequently Asked Questions</h2>
          <p className="text-gray-600 text-lg">
            Find answers to common questions about our services
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`} className="border-b">
                <AccordionTrigger className="text-left font-medium text-gray-900 hover:text-primary">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
        
        <div className="mt-12 bg-primary-50 rounded-lg border border-primary-100 p-6 max-w-3xl mx-auto">
          <h3 className="font-medium text-xl text-center text-primary mb-4">Still have questions?</h3>
          <p className="text-center text-gray-600 mb-6">
            Contact us directly and we'll be happy to assist you with any queries you may have.
          </p>
          <div className="flex justify-center">
            <a 
              href="#contact" 
              className="inline-block bg-gradient-to-r from-[#D4AF37] to-[#B8860B] text-white px-6 py-3 rounded-md font-medium text-sm transition-all duration-300 hover:shadow-lg hover:shadow-[#D4AF37]/20 hover:scale-105"
            >
              Contact Us
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Faq;
